In [1]:
from ckmeans_1d_dp import ckmeans

In [2]:
import numpy as np

In [3]:
x = np.array([[1, 2, 3, 40, 50, -40],
              [1, 2, 20, 21, 3, 0],
              [100, 100, 100, 4, 5, 1],
             ])

In [4]:
result = ckmeans(x)

In [5]:
for field, value in result._asdict().items():
    print(field)
    print(value)

cluster
[[1 1 1 2 2 0]
 [0 0 1 1 0 0]
 [1 1 1 0 0 0]]
centers
[[-40.           2.          45.           0.           0.
    0.           0.           0.           0.        ]
 [  1.5         20.5          0.           0.           0.
    0.           0.           0.           0.        ]
 [  3.33333333 100.           0.           0.           0.
    0.           0.           0.           0.        ]]
withinss
[[ 0.          2.         50.          0.          0.          0.
   0.          0.          0.        ]
 [ 5.          0.5         0.          0.          0.          0.
   0.          0.          0.        ]
 [ 8.66666667  0.          0.          0.          0.          0.
   0.          0.          0.        ]]
size
[[1. 3. 2. 0. 0. 0. 0. 0. 0.]
 [4. 2. 0. 0. 0. 0. 0. 0. 0.]
 [3. 3. 0. 0. 0. 0. 0. 0. 0.]]
totss
[ 865.22222222   81.13888889 2337.55555556]
tot_withinss
[52.          5.5         8.66666667]
betweensss
[ 813.22222222   75.63888889 2328.88888889]
